language: python
dist: xenial
sudo: true

python:
  - 3.8.5

env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1

install:
  - pip install pipenv
  - pipenv sync -d
  - pip install codecov
  - pipenv install 'python-decouple'
  - cp contrib/env-sample .env


script:
  - pipenv run flake8
  - pipenv run pytest --cov=pysite

after_success:
  - pipenv run codecov
  - bash <(curl -s https://codecov.io/bash)



